name: Auto Update SIF Scheme Data

on:
  schedule:
    - cron: '30 20 * * 6'   
  workflow_dispatch:

jobs:
  update-scheme-data:
    runs-on: ubuntu-latest
    
    # Run if triggered manually or via schedule
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run SIF Scheme Pipeline
        run: |
          python scripts/fetch_scheme_data.py
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          git add data/sif/scheme/details/
          
          if git diff --cached --quiet; then
            echo "No new Scheme updates."
          else
            git commit -m "Auto update Scheme data"
            git push
            echo "Successfully updated and pushed new Scheme data."
          fi
