name: Auto Update SIF NAV Data

on:
  schedule:
    - cron: '30 14 * * 2-6'
  workflow_dispatch:

jobs:
  update-nav-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run SIF NAV Pipeline
        run: |
          python scripts/fetch_sif_nav.py
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          git add data/sif/scheme/nav/
          
          if git diff --cached --quiet; then
            echo "No new NAV updates."
          else
            git commit -m "Auto update NAV data"
            git push
            echo "Successfully updated and pushed new NAV data."
          fi
